#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.rvm/bin # Add RVM to PATH for scripting
  /opt/sublime_text_3
  $HOME/.git-aliae/bin
  $HOME/android/sdk/{tools,platform-tools}
  $HOME/node-v0.10.1-linux-x64/bin    # Add node to PATH
  $HOME/java/gradle-1.7/bin
  $HOME/java/apache-ant-1.9.2/bin
  /usr/local/{bin,sbin}
  $path
)

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
