#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
pyenv() { source $HOME/python_envs/$*/bin/activate; }
if [[ -s "${ZDOTDIR:-$HOME}/.local_aliases" ]]; then
  source "${ZDOTDIR:-$HOME}/.local_aliases"
fi

dev() {
  if [ "2" -ne "$#" ]; then
    echo "Usage: dev start|stop Product-folder-path" && return 1
  elif [ "start" == "$1" ]; then
    $HOME/bin/dev_start.sh $2
  else
    echo "$1 method not implmented"
  fi
}

# Aliases
alias grhu='git reset --hard upstream/master'

